image: debian:stretch
variables:
## Enable under shared runner 
## In gitlab/variables : declare Variable File Variable named http_proxy_shared, and no_proxy_shared
  http_proxy: $http_proxy_shared
  https_proxy: $http_proxy_shared
  no_proxy: $no_proxy_shared
  HTTP_PROXY: $http_proxy_shared
  HTTPS_PROXY: $http_proxy_shared
  NO_PROXY: $no_proxy_shared

## In gitlab/variables : declare Variable File Type named BUILD_CONFIG
##  containing internal NPM_REGISTRY, SASS_REGISTRY, PYPI_URL, PYPI_HOST, RUBY_URL,, CYPRESS_DOWNLOAD_MIRROR, MIRROR_DEBIAN
##   MIRROR_DOCKER, MIRROR_DOCKER_KEY
  BUILD_CONFIG_FILE: $BUILD_CONFIG

# GIT_CURL_VERBOSE: "1"
# GIT_DEBUG_LOOKUP: "1"
# GIT_TRANSLOOP_DEBUG: "1"
# GIT_TRANSPORT_HELPER_DEBUG: "1"

stages:
  - build

default:
  tags:
    - shared
  before_script:
    - echo "# Before script"
    - echo "$BUILD_CONFIG_FILE" > .build_config
    - source .build_config
    - time sudo -E /bin/bash -c 'ci/before_scripts.sh'

build_beat_stack:
  stage: build
  script:
    - echo "# Build"
